module Fog
  module Oracle
    module BackingDeviceType
      UNSUPPORTED = 'UNSUPPORTED'
      LOCALDEVICE_SINGLE = 'LOCALDEVICE_SINGLE'
      LOCALDEVICE_MULTI = 'LOCALDEVICE_MULTI'
      REMOTEDEVICE_SINGLE = 'REMOTEDEVICE_SINGLE'
      REMOTEDEVICE_MULTI = 'REMOTEDEVICE_MULTI'
      INVALID = 'INVALID'
    end
  end
end
