module Fog
  module Oracle
    module StatisticType
      CPU_UTILIZATION = 'CPU_UTILIZATION'
      CPU_COUNT = 'CPU_COUNT'
      CPU_TIME = 'CPU_TIME'
      MEMORY_USED = 'MEMORY_USED'
      FREE_SWAP = 'FREE_SWAP'
      NETWORK_SENT = 'NETWORK_SENT'
      NETWORK_RECEIVED = 'NETWORK_RECEIVED'
      DISK_READ = 'DISK_READ'
      DISK_WRITE = 'DISK_WRITE'
      PER_CPU_UTILIZATION = 'PER_CPU_UTILIZATION'
      MEMORY_UTILIZATION = 'MEMORY_UTILIZATION'
      FILE_SYSTEM_SPACE_AVAILABLE = 'FILE_SYSTEM_SPACE_AVAILABLE'
    end
  end
end
