module Fog
  module Oracle
    module StorageAbility
      UNKNOWN = 'UNKNOWN'
      SNAPSHOT = 'SNAPSHOT'
      SNAPSHOT_CUSTOM_NAME = 'SNAPSHOT_CUSTOM_NAME'
      SNAPSHOT_SYNCHRONOUS = 'SNAPSHOT_SYNCHRONOUS'
      CLONE = 'CLONE'
      CLONE_CUSTOM_NAME = 'CLONE_CUSTOM_NAME'
      CLONE_SYNCHRONOUS = 'CLONE_SYNCHRONOUS'
      RESIZE = 'RESIZE'
      RESIZE_SYNCHRONOUS = 'RESIZE_SYNCHRONOUS'
      CLONE_SPLITTING = 'CLONE_SPLITTING'
      CLONE_SPLITTING_SYNCHRONOUS = 'CLONE_SPLITTING_SYNCHRONOUS'
      CLONE_SPLITTING_WHILE_OPEN = 'CLONE_SPLITTING_WHILE_OPEN'
      SNAPSHOT_CLONE = 'SNAPSHOT_CLONE'
      SNAPSHOT_CLONE_SYNCHRONOUS = 'SNAPSHOT_CLONE_SYNCHRONOUS'
      STORAGE_NAME_REQUIRED = 'STORAGE_NAME_REQUIRED'
      ACCESS_CONTROL = 'ACCESS_CONTROL'
      BACKING_DEVICE_TYPE = 'BACKING_DEVICE_TYPE'
    end
  end
end
